export const FETCH_TRENDING_MOVIES = "FETCH_TRENDING_MOVIES";
export const FETCH_SECOND_GENRE = "FETCH_SECOND_GENRE";
export const FETCH_THIRD_GENRE = "FETCH_THIRD_GENRE";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
